---

- name: supervisor start
  service: name="{{ supervisor_service }}" state=started
  when: supervisor_started

- name: supervisor stop
  service: name="{{ supervisor_service }}" state=stopped

- name: supervisor restart
  service: name="{{ supervisor_service }}" state=restarted
  when: supervisor_started

- name: reload systemd
  systemd:
    daemon_reload: yes

# vi:ts=2:sw=2:et:ft=yaml
